// packages/guest-app-3/src/App.vue
<template>
  <div id="app">
    <header>
      <h1>Vue Analytics App</h1>
      <nav>
        <RouterLink to="/dashboard">Dashboard</RouterLink> |
        <RouterLink to="/reports">Reports</RouterLink>
      </nav>
    </header>
    <RouterView />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue'
import { useRouter, useRoute } from 'vue-router'

const isInBottomSheet = ref(false)

const router = useRouter()
const route = useRoute()

const hostOrigin = import.meta.env.VITE_HOST_ORIGIN || window.location.origin

const handleBottomSheetMode = (event: any) => {
  isInBottomSheet.value = event.detail.isBottomSheet
}

const handleHostNavigation = (event: CustomEvent) => {
  const { path } = event.detail
  console.log(`Vue App received navigation request to: ${path}`)
  
  if (route.path !== path) {
    router.push(path)
  }
}

// Listen for navigation commands from the host
onMounted(() => {
  window.addEventListener('appNavigation', handleHostNavigation as EventListener)
  window.addEventListener('bottomSheetMode', handleBottomSheetMode)
  
  // Send ready message to the host
  if (window.parent !== window) {
    window.parent.postMessage({
      type: 'ready',
      guestId: 'app3',
      currentPath: route.path
    }, hostOrigin)
  }
})

onUnmounted(() => {
  window.removeEventListener('appNavigation', handleHostNavigation as EventListener)
  window.removeEventListener('bottomSheetMode', handleBottomSheetMode)
})

watch(() => route.path, (newPath) => {
  console.log(`Route changed to: ${newPath}`)
  
  if (window.parent !== window) {
    window.parent.postMessage({
      type: 'routeChange',
      path: newPath,
      appId: 'app3'
    }, hostOrigin)
  }
})
</script>

<style scoped>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #2c3e50;
  margin: 0;
  padding: 20px;
}

header {
  margin-bottom: 20px;
}

nav {
  padding: 15px 0;
}

nav a {
  color: #42b883;
  text-decoration: none;
  margin: 0 10px;
  font-weight: bold;
}

nav a.router-link-active {
  color: #359268;
  border-bottom: 2px solid #359268;
}
</style>

// packages/guest-app-1/src/App.tsx
import { useEffect } from "react";
import {
  Routes,
  Route,
  Navigate,
  useLocation,
  useNavigate,
} from "react-router-dom";
import { openAppInBottomSheet } from "../../core-lib/src/bottomSheet";

const Dashboard = () => (
  <div>
    <h2>App 1: Dashboard</h2>
    <button
      onClick={() => {
        openAppInBottomSheet("app3", "/reports", "60vh");
      }}
    >
      Test
    </button>
  </div>
);
const Settings = () => <h2>App 1: Settings</h2>;
const NotFound = () => <h2>App 1: Not Found</h2>;

const hostOrigin = import.meta.env.VITE_HOST_ORIGIN || window.location.origin;

function App() {
  const location = useLocation();
  const navigate = useNavigate();

  console.log("Guest App 1 rendering at path:", location.pathname);

  // Listen for navigation events from the host
  useEffect(() => {
    const handleNavigation = (event: CustomEvent<{ path: string }>) => {
      const path = event.detail.path;
      console.log(`Received navigation request to: ${path}`);

      if (location.pathname !== path) {
        console.log(`Navigating from ${location.pathname} to ${path}`);
        navigate(path);
      }
    };

    window.addEventListener("appNavigation", handleNavigation as EventListener);
    return () => {
      window.removeEventListener(
        "appNavigation",
        handleNavigation as EventListener
      );
    };
  }, [navigate, location.pathname]);

  // Report route changes back to the host
  useEffect(() => {
    console.log(`Route changed to: ${location.pathname}`);

    // Send message to host about the route change
    if (window.parent !== window) {
      window.parent.postMessage(
        {
          type: "routeChange",
          path: location.pathname,
          appId: "app1",
        },
        hostOrigin
      );
    }
  }, [location.pathname]);

  return (
    <div>
      <h1>Guest App 1</h1>
      <div
        style={{ background: "#f0f0f0", padding: "8px", marginBottom: "16px" }}
      >
        <p>Current path: {location.pathname}</p>
      </div>

      <nav>
        <button onClick={() => navigate("/dashboard")}>Dashboard</button>
        <button onClick={() => navigate("/settings")}>Settings</button>
      </nav>

      <Routes>
        <Route path="/dashboard" element={<Dashboard />} />
        <Route path="/settings" element={<Settings />} />
        <Route path="/" element={<Navigate to="/dashboard" replace />} />
        <Route path="*" element={<NotFound />} />
      </Routes>
    </div>
  );
}

export default App;
